name: supaauth
description: "A basic SupaBase auth package"
version: 0.0.1
homepage: https://github.com/chrismercredi
publish_to: 

# Use this command to run in GitHub codespace:
# flutter run -d web-server --web-hostname=0.0.0.0 --web-port=3000

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  gap: ^3.0.1
  supabase_flutter: ^1.10.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
