name: supaauth
version: 0.1.0-alpha.1
description: "A basic SupaBase auth package"
homepage: https://github.com/chrismercredi
repository: https://github.com/chrismercredi/supaauth
publish_to:
screenshots:
  - path: screenshots/login_page.png
    description: 'A picture of the Login page using the android emulator'
  - path: screenshots/sign_up_page.png
    description: 'A picture of a sign up page using the android emulator'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  supabase_flutter: ^1.10.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
  
  fonts: 
    - family: Staatliches
      fonts:
        - asset: assets/fonts/Staatliches/Staatliches-Regular.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
        - asset: assets/fonts/Noto_Sans/NotoSans-VariableFont_wdth,wght.ttf
          
        